# App Info
ios_app_id: 6740043033 # Required. # 1457483172 #1234793120   Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://apps.apple.com/ca/app/bike-hike-brezza/id6740043033
Bike & Hike: Brezza
playstore_link: # Enter Google Play Store URL.
presskit_download_link: assets/TrailCast-presskit.zip
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
policy: /policy/
permalink: /:categories/:title/

app_icon: assets/appIcon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Brezza # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Plan your routes - Be ready for every ride, ski, hike

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Gustavo
your_link:
your_city: Vancouver, BC
email_address:
facebook_username:
instagram_username:
twitter_username: ferrufinodlf
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Add a waypoint or Import routes from different sources
    description: Strava activities or routes, GPX files, Apple fitness Workouts. 🚴⛷️🏃🏼‍♀️🏃🏻‍♂️
    fontawesome_icon_name: road

  - title: Weather Forecast
    description: See hourly and daily forecast with detailed weather conditions at the lowest & highest points.
    fontawesome_icon_name: cloud-sun-rain

  - title: Vista
    description: Tailored weather forecasts for the exact time and location of your route, featuring interactive charts and detailed conditions 💯
    fontawesome_icon_name: chart-line

  - title: Planner
    description: Add things to pack! Specify quantities needed.
    fontawesome_icon_name: list

  - title: # New Feature title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.3
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.5

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-redirect-from
